export const courtsSeed = [
  {
    id: 'court-1',
    name: 'Arena Smouha',
    area: 'smouha',
    areaLabel: 'سموحة',
    sport: 'football',
    sportLabel: 'كرة قدم',
    price: 'mid',
    priceLabel: 'متوسط',
    badge: 'متاح اليوم',
    description: 'ملعب خماسي بمواعيد مرنة، إضاءة قوية، وحجز فوري بدون تعارض.',
  },
  {
    id: 'court-2',
    name: 'Cairo Street Padel',
    area: 'sidi-gaber',
    areaLabel: 'سيدي جابر',
    sport: 'padel',
    sportLabel: 'بادل',
    price: 'high',
    priceLabel: 'مرتفع',
    badge: 'Premium',
    description: 'تجربة بادل مميزة مع نظام عربون وتأكيد تلقائي للحجز.',
  },
  {
    id: 'court-3',
    name: 'Seaside Billiards Hall',
    area: 'san-stefano',
    areaLabel: 'سان ستيفانو',
    sport: 'billiards',
    sportLabel: 'بلياردو',
    price: 'mid',
    priceLabel: 'متوسط',
    badge: 'Indoor',
    description: 'صالات هادئة للحجز بالساعة مع أوقات مخصصة للبطولات الودية.',
  },
  {
    id: 'court-4',
    name: 'Abu Qir Play Zone',
    area: 'abor',
    areaLabel: 'أبو قير',
    sport: 'playstation',
    sportLabel: 'بلايستيشن',
    price: 'low',
    priceLabel: 'منخفض',
    badge: 'Offers',
    description: 'جلسات لعب جماعية وعروض منتصف الأسبوع لجذب المستخدمين الشباب.',
  },
]

export const maintenanceSeed = [
  {
    id: 'job-1',
    title: 'صيانة إضاءة كشافات',
    category: 'إضاءة',
    vendorName: 'Arena Smouha',
    customerName: 'سموحة كورت',
    phone: '01000000001',
    status: 'NEW',
    notes: 'الكشاف الشمال يحتاج فحص واستبدال درايفر.',
  },
  {
    id: 'job-2',
    title: 'ترميم عشب صناعي',
    category: 'أرضيات',
    vendorName: 'Jaber Court Club',
    customerName: 'Jaber Court Club',
    phone: '01000000002',
    status: 'ACCEPTED',
    notes: 'المنطقة الوسطى فيها تآكل واضح.',
  },
]
