export const courtsSeed = [
  {
    id: 'court-1',
    name: 'Arena Smouha',
    area: 'smouha',
    areaLabel: 'سموحة',
    sport: 'football',
    sportLabel: 'كرة قدم',
    price: 'mid',
    priceLabel: 'متوسط',
    badge: 'متاح اليوم',
    description: 'ملعب خماسي بمواعيد مرنة، إضاءة قوية، وحجز فوري بدون تعارض.',
  },
  {
    id: 'court-2',
    name: 'Cairo Street Padel',
    area: 'sidi-gaber',
    areaLabel: 'سيدي جابر',
    sport: 'padel',
    sportLabel: 'بادل',
    price: 'high',
    priceLabel: 'مرتفع',
    badge: 'Premium',
    description: 'تجربة بادل مميزة مع نظام عربون وتأكيد تلقائي للحجز.',
  },
  {
    id: 'court-3',
    name: 'Seaside Billiards Hall',
    area: 'san-stefano',
    areaLabel: 'سان ستيفانو',
    sport: 'billiards',
    sportLabel: 'بلياردو',
    price: 'mid',
    priceLabel: 'متوسط',
    badge: 'Indoor',
    description: 'صالات هادئة للحجز بالساعة مع أوقات مخصصة للبطولات الودية.',
  },
  {
    id: 'court-4',
    name: 'Abu Qir Play Zone',
    area: 'abor',
    areaLabel: 'أبو قير',
    sport: 'playstation',
    sportLabel: 'بلايستيشن',
    price: 'low',
    priceLabel: 'منخفض',
    badge: 'Offers',
    description: 'جلسات لعب جماعية وعروض منتصف الأسبوع لجذب المستخدمين الشباب.',
  },
]

export const maintenanceSeed = [
  {
    id: 'job-1',
    title: 'صيانة إضاءة كشافات',
    category: 'إضاءة',
    vendorName: 'Arena Smouha',
    customerName: 'سموحة كورت',
    phone: '01000000001',
    status: 'NEW',
    notes: 'الكشاف الشمال يحتاج فحص واستبدال درايفر.',
  },
  {
    id: 'job-2',
    title: 'ترميم عشب صناعي',
    category: 'أرضيات',
    vendorName: 'Jaber Court Club',
    customerName: 'Jaber Court Club',
    phone: '01000000002',
    status: 'ACCEPTED',
    notes: 'المنطقة الوسطى فيها تآكل واضح.',
  },
]

export const usersSeed = [
  {
    id: 'user-vendor-1',
    name: 'Smouha Sports Group',
    phone: '01000000010',
    role: 'VENDOR',
    isActive: true,
  },
  {
    id: 'user-tech-1',
    name: 'Alex Repair Team',
    phone: '01000000011',
    role: 'TECHNICIAN',
    isActive: true,
  },
  {
    id: 'user-admin-1',
    name: 'Platform Admin',
    phone: '01000000013',
    role: 'ADMIN',
    isActive: true,
  },
  {
    id: 'user-player-1',
    name: 'Ahmed Player',
    phone: '01000000012',
    role: 'PLAYER',
    isActive: true,
  },
]

export const bookingsSeed = [
  {
    id: 'booking-1',
    courtId: 'court-1',
    userId: 'user-player-1',
    customerName: 'Ahmed Player',
    email: 'ahmed.player@example.com',
    phone: '01000000012',
    startsAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 3.5 * 60 * 60 * 1000).toISOString(),
    status: 'CONFIRMED',
    notes: 'مباراة خماسية مع الأصدقاء.',
    amountCents: 18000,
  },
  {
    id: 'booking-2',
    courtId: 'court-1',
    userId: 'user-player-1',
    customerName: 'Ahmed Player',
    email: 'ahmed.player@example.com',
    phone: '01000000012',
    startsAt: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 7.5 * 60 * 60 * 1000).toISOString(),
    status: 'PENDING',
    notes: 'حجز مسائي احتياطي.',
    amountCents: 18000,
  },
  {
    id: 'booking-3',
    courtId: 'court-2',
    userId: null,
    customerName: 'Mona Guest',
    email: 'mona.guest@example.com',
    phone: '01000000014',
    startsAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 25.5 * 60 * 60 * 1000).toISOString(),
    status: 'CONFIRMED',
    notes: 'جلسة تدريب بادل.',
    amountCents: 26000,
  },
  {
    id: 'booking-4',
    courtId: 'court-3',
    userId: null,
    customerName: 'Booking Hold',
    email: null,
    phone: '01000000015',
    startsAt: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 49.5 * 60 * 60 * 1000).toISOString(),
    status: 'CANCELLED',
    notes: 'تم الإلغاء من العميل.',
    amountCents: 18000,
  },
  {
    id: 'booking-5',
    courtId: 'court-1',
    userId: 'user-player-1',
    customerName: 'Ahmed Player',
    email: 'ahmed.player@example.com',
    phone: '01000000012',
    startsAt: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
    status: 'CONFIRMED',
    notes: 'سلسلة تدريب أسبوعية.',
    amountCents: 18000,
    seriesId: 'series-demo-weekly',
    repeatPattern: 'WEEKLY',
    repeatCount: 4,
    occurrenceIndex: 0,
  },
]

export const waitlistSeed = [
  {
    id: 'wait-1',
    courtId: 'court-1',
    userId: 'user-player-1',
    customerName: 'Ahmed Player',
    email: 'ahmed.player@example.com',
    phone: '01000000012',
    startsAt: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 5.5 * 60 * 60 * 1000).toISOString(),
    status: 'WAITING',
    notes: 'لو فاضي أي slot، نبعت إشعار.',
    repeatPattern: 'NONE',
    repeatCount: 1,
    seriesId: 'wait-demo-1',
  },
  {
    id: 'wait-2',
    courtId: 'court-2',
    userId: null,
    customerName: 'Mona Guest',
    email: 'mona.guest@example.com',
    phone: '01000000014',
    startsAt: new Date(Date.now() + 30 * 60 * 60 * 1000).toISOString(),
    endsAt: new Date(Date.now() + 31.5 * 60 * 60 * 1000).toISOString(),
    status: 'NOTIFIED',
    notes: 'تم إخطارها بوجود فتحة لاحقًا.',
    repeatPattern: 'WEEKLY',
    repeatCount: 3,
    seriesId: 'wait-demo-2',
    notifiedAt: new Date().toISOString(),
  },
]
